name: Linux Build CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]    
    
jobs:
  build:
    name: Linux Build CI
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-22.04
    
    strategy:
      matrix:
        # Might want debug once release works
        configuration: ['release'] # , 'debug']
        platform: ['x64']
        
    steps:   
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
          fetch-depth: '0'

      #- name: prepare
      #  run: |
      #    sudo apt-get install docker.io
          
      - name: build
        run: |
          sudo docker run -t --rm -w /io -v `pwd`:/io ghcr.io/phusion/holy-build-box/hbb-64 /hbb_exe/activate-exec bash /io/build-hbb-linux.sh ${{matrix.platform}} ${{matrix.configuration}}
          # sudo docker run -t -i --rm -w /io -v `pwd`:/io ghcr.io/phusion/holy-build-box/hbb-64 /hbb_exe/activate-exec bash /io/build-hbb-linux.sh ${{matrix.platform}} ${{matrix.configuration}}
          
      #- name: premake
      #  run: |
      # 
      #    PREMAKE=external/slang-binaries/premake/premake-5.0.0-alpha16/bin/linux-64/premake5
      #    chmod u+x ${PREMAKE}
      #    ${PREMAKE} gmake --deps=true --no-progress=true          
      #- name: Build
      #  run: |
      #    make config=${{matrix.configuration}}_x64 -j`nproc`
          
      - uses: actions/upload-artifact@v3
        with:
          name: slang-llvm-linux-${{matrix.platform}}-${{matrix.configuration}}
          path: | 
            bin/**/*.so
            LICENSE
            README.md    
