name: Linux Build CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]    
    
jobs:
  build:
    name: Linux Build CI
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-22.04
    
    strategy:
      matrix:
        # Might want debug once release works
        configuration: ['release'] # , 'debug']
        
    steps:   
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
          fetch-depth: '0'

      - name: premake
        run: |
          PREMAKE=external/slang-binaries/premake/premake-5.0.0-alpha16/bin/linux-64/premake5
          chmod u+x ${PREMAKE}
          ${PREMAKE} gmake --deps=true --no-progress=true          

      - name: Build
        run: |
          make config=${{matrix.configuration}}_x64 -j`nproc`
          
      - name: archive
        id: archive
        run: |
          echo "achiving files..."
          
          ARCH_NAME=`uname -p`
          PLATFORM_NAME="linux-x86_64"
          TAG_NAME=`git show -s --format="%h"`
          SLANG_LLVM_VERSION=${TAG_NAME}
          
          echo "tag:$TAG_NAME"
          echo "slang-llvm-version:$LLVM_VERSION"
          
          BIN_ARCHIVE="slang-llvm-$TAG_NAME-$PLATFORM_NAME-${{matrix.configuration}}.zip"

          zip "$BIN_ARCHIVE" README.md
          zip "$BIN_ARCHIVE" LICENSE
          zip "$BIN_ARCHIVE" -r bin/*/*/*.so
          
          echo "name=BINARY_ARCHIVE::$BIN_ARCHIVE"
          echo "::set-output name=BINARY_ARCHIVE::$BIN_ARCHIVE"    
          
      - uses: actions/upload-artifact@v3
        with:
          name: slang-llvm-${{matrix.configuration}}-${{matrix.platform}}-${{matrix.compiler}}
          path: ${{ steps.archive.outputs.BINARY_ARCHIVE }}      
