name: Linux Build CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]    
    
jobs:
  build:
    name: Linux Build CI
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        # Might want debug once release works
        configuration: ['release'] # , 'debug']
        
    steps:   
      - uses: actions/checkout@v2.3.4
        with:
          submodules: 'true'
          fetch-depth: '0'

      - name: premake
        run: |
          PREMAKE=external/slang-binaries/premake/premake-5.0.0-alpha16/bin/linux-64/premake5
          chmod u+x ${PREMAKE}
          ${PREMAKE} gmake --deps=true --no-progress=true          

      - name: Build
        run: |
          make config=${{matrix.configuration}}_x64 -j`nproc`
