name: Windows Build CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ] 

jobs:
  build:
    name: Windows Build CI
    runs-on: windows-latest
    strategy:
      matrix:
        configuration: ['Release']
        # We can't build aarch64 LLVM for windows currently, so don't have 'aarch64' 
        platform: ['x64', 'Win32'] 
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
          fetch-depth: '0'
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1
      - name: premake
        run:
          .\premake.bat vs2019 --deps=true --no-progress=true --arch=${{matrix.platform}}
      - name: msbuild
        run:
          MSBuild.exe slang-llvm.sln -v:m -m -property:Configuration=${{matrix.configuration}} -property:Platform=${{matrix.platform}} -property:WindowsTargetPlatformVersion=10.0.19041.0
          